project_id = "qwqkrsvbmabodvmfktvj"

[functions.vocabulary-ai]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.get-unlocked-words]
verify_jwt = false

[functions.league-transition]
verify_jwt = false

[functions.reset-daily-xp]
verify_jwt = false
