project_id = "qwqkrsvbmabodvmfktvj"

[functions.vocabulary-ai]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.get-unlocked-words]
verify_jwt = false

[functions.league-transition]
verify_jwt = false

[functions.reset-daily-xp]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.groq-chat]
verify_jwt = false

[functions.fetch-word-image]
verify_jwt = false

[functions.generate-ai-image]
verify_jwt = false

[functions.generate-content]
verify_jwt = false

[functions.generate-hf-image]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false
